[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[server]
headless = true
port = 8501
address = "localhost"

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"